services:
  - type: web
    name: dad-jokes-sms-api
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    plan: free 