services:
  - type: web
    name: dad-jokes-sms-api
    env: node
    buildCommand: npm install && npm run build:server
    startCommand: node dist/server.js
    envVars:
      - key: NODE_ENV
        value: production
    plan: free 