name: Deploy Server to Render

on:
  push:
    branches: [ main ]
    paths:
      - 'src/server.ts'
      - 'src/jokes.ts'
      - '.github/workflows/deploy-server.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Render
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }} 